resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/Hylke1982/TDDTrainingApplication.git
    branch: concourse


jobs:

- name: build
  plan:
  - get: source-code
    triggger: true
  - task: compile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}
      inputs:
        - name: source-code
      run:
        path: mvn
        args: ["-f", "source-code/pom.xml","compile"]

- name: test
  plan:
  - get: source-code
    trigger: true
    passed: [build]
  - task: unit-test
    config:
      inputs:
        - name: source-code
      file: source-code/concourse/maven-test.yml